spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  sql:
    init:
      mode: never
      encoding: UTF-8

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    check-template-location: true
    cache: true
    order: 0

logging:
  level:
    org:
      hibernate:
        SQL: debug
    root: info

server:
  port: 8081
